//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by conversion-gen. DO NOT EDIT.

package v1alpha

import (
	custom "custom-apiserver/pkg/apis/custom"
	unsafe "unsafe"

	conversion "k8s.io/apimachinery/pkg/conversion"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

func init() {
	localSchemeBuilder.Register(RegisterConversions)
}

// RegisterConversions adds conversion functions to the given scheme.
// Public to allow building arbitrary schemes.
func RegisterConversions(s *runtime.Scheme) error {
	if err := s.AddGeneratedConversionFunc((*JenkinsServerInstance)(nil), (*custom.JenkinsServerInstance)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha_JenkinsServerInstance_To_custom_JenkinsServerInstance(a.(*JenkinsServerInstance), b.(*custom.JenkinsServerInstance), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*custom.JenkinsServerInstance)(nil), (*JenkinsServerInstance)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_custom_JenkinsServerInstance_To_v1alpha_JenkinsServerInstance(a.(*custom.JenkinsServerInstance), b.(*JenkinsServerInstance), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*JenkinsService)(nil), (*custom.JenkinsService)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha_JenkinsService_To_custom_JenkinsService(a.(*JenkinsService), b.(*custom.JenkinsService), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*custom.JenkinsService)(nil), (*JenkinsService)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_custom_JenkinsService_To_v1alpha_JenkinsService(a.(*custom.JenkinsService), b.(*JenkinsService), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*JenkinsServiceSpec)(nil), (*custom.JenkinsServiceSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha_JenkinsServiceSpec_To_custom_JenkinsServiceSpec(a.(*JenkinsServiceSpec), b.(*custom.JenkinsServiceSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*custom.JenkinsServiceSpec)(nil), (*JenkinsServiceSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_custom_JenkinsServiceSpec_To_v1alpha_JenkinsServiceSpec(a.(*custom.JenkinsServiceSpec), b.(*JenkinsServiceSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*JenkinsServiceStatus)(nil), (*custom.JenkinsServiceStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha_JenkinsServiceStatus_To_custom_JenkinsServiceStatus(a.(*JenkinsServiceStatus), b.(*custom.JenkinsServiceStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*custom.JenkinsServiceStatus)(nil), (*JenkinsServiceStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_custom_JenkinsServiceStatus_To_v1alpha_JenkinsServiceStatus(a.(*custom.JenkinsServiceStatus), b.(*JenkinsServiceStatus), scope)
	}); err != nil {
		return err
	}
	return nil
}

func autoConvert_v1alpha_JenkinsServerInstance_To_custom_JenkinsServerInstance(in *JenkinsServerInstance, out *custom.JenkinsServerInstance, s conversion.Scope) error {
	out.Cpu = in.Cpu
	out.Running = in.Running
	return nil
}

// Convert_v1alpha_JenkinsServerInstance_To_custom_JenkinsServerInstance is an autogenerated conversion function.
func Convert_v1alpha_JenkinsServerInstance_To_custom_JenkinsServerInstance(in *JenkinsServerInstance, out *custom.JenkinsServerInstance, s conversion.Scope) error {
	return autoConvert_v1alpha_JenkinsServerInstance_To_custom_JenkinsServerInstance(in, out, s)
}

func autoConvert_custom_JenkinsServerInstance_To_v1alpha_JenkinsServerInstance(in *custom.JenkinsServerInstance, out *JenkinsServerInstance, s conversion.Scope) error {
	out.Cpu = in.Cpu
	out.Running = in.Running
	return nil
}

// Convert_custom_JenkinsServerInstance_To_v1alpha_JenkinsServerInstance is an autogenerated conversion function.
func Convert_custom_JenkinsServerInstance_To_v1alpha_JenkinsServerInstance(in *custom.JenkinsServerInstance, out *JenkinsServerInstance, s conversion.Scope) error {
	return autoConvert_custom_JenkinsServerInstance_To_v1alpha_JenkinsServerInstance(in, out, s)
}

func autoConvert_v1alpha_JenkinsService_To_custom_JenkinsService(in *JenkinsService, out *custom.JenkinsService, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v1alpha_JenkinsServiceSpec_To_custom_JenkinsServiceSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_v1alpha_JenkinsServiceStatus_To_custom_JenkinsServiceStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha_JenkinsService_To_custom_JenkinsService is an autogenerated conversion function.
func Convert_v1alpha_JenkinsService_To_custom_JenkinsService(in *JenkinsService, out *custom.JenkinsService, s conversion.Scope) error {
	return autoConvert_v1alpha_JenkinsService_To_custom_JenkinsService(in, out, s)
}

func autoConvert_custom_JenkinsService_To_v1alpha_JenkinsService(in *custom.JenkinsService, out *JenkinsService, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_custom_JenkinsServiceSpec_To_v1alpha_JenkinsServiceSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_custom_JenkinsServiceStatus_To_v1alpha_JenkinsServiceStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_custom_JenkinsService_To_v1alpha_JenkinsService is an autogenerated conversion function.
func Convert_custom_JenkinsService_To_v1alpha_JenkinsService(in *custom.JenkinsService, out *JenkinsService, s conversion.Scope) error {
	return autoConvert_custom_JenkinsService_To_v1alpha_JenkinsService(in, out, s)
}

func autoConvert_v1alpha_JenkinsServiceSpec_To_custom_JenkinsServiceSpec(in *JenkinsServiceSpec, out *custom.JenkinsServiceSpec, s conversion.Scope) error {
	out.InstanceAmount = in.InstanceAmount
	out.InstanceCpu = in.InstanceCpu
	return nil
}

// Convert_v1alpha_JenkinsServiceSpec_To_custom_JenkinsServiceSpec is an autogenerated conversion function.
func Convert_v1alpha_JenkinsServiceSpec_To_custom_JenkinsServiceSpec(in *JenkinsServiceSpec, out *custom.JenkinsServiceSpec, s conversion.Scope) error {
	return autoConvert_v1alpha_JenkinsServiceSpec_To_custom_JenkinsServiceSpec(in, out, s)
}

func autoConvert_custom_JenkinsServiceSpec_To_v1alpha_JenkinsServiceSpec(in *custom.JenkinsServiceSpec, out *JenkinsServiceSpec, s conversion.Scope) error {
	out.InstanceAmount = in.InstanceAmount
	out.InstanceCpu = in.InstanceCpu
	return nil
}

// Convert_custom_JenkinsServiceSpec_To_v1alpha_JenkinsServiceSpec is an autogenerated conversion function.
func Convert_custom_JenkinsServiceSpec_To_v1alpha_JenkinsServiceSpec(in *custom.JenkinsServiceSpec, out *JenkinsServiceSpec, s conversion.Scope) error {
	return autoConvert_custom_JenkinsServiceSpec_To_v1alpha_JenkinsServiceSpec(in, out, s)
}

func autoConvert_v1alpha_JenkinsServiceStatus_To_custom_JenkinsServiceStatus(in *JenkinsServiceStatus, out *custom.JenkinsServiceStatus, s conversion.Scope) error {
	out.ApprovalStatus = in.ApprovalStatus
	out.Instances = *(*[]custom.JenkinsServerInstance)(unsafe.Pointer(&in.Instances))
	return nil
}

// Convert_v1alpha_JenkinsServiceStatus_To_custom_JenkinsServiceStatus is an autogenerated conversion function.
func Convert_v1alpha_JenkinsServiceStatus_To_custom_JenkinsServiceStatus(in *JenkinsServiceStatus, out *custom.JenkinsServiceStatus, s conversion.Scope) error {
	return autoConvert_v1alpha_JenkinsServiceStatus_To_custom_JenkinsServiceStatus(in, out, s)
}

func autoConvert_custom_JenkinsServiceStatus_To_v1alpha_JenkinsServiceStatus(in *custom.JenkinsServiceStatus, out *JenkinsServiceStatus, s conversion.Scope) error {
	out.ApprovalStatus = in.ApprovalStatus
	out.Instances = *(*[]JenkinsServerInstance)(unsafe.Pointer(&in.Instances))
	return nil
}

// Convert_custom_JenkinsServiceStatus_To_v1alpha_JenkinsServiceStatus is an autogenerated conversion function.
func Convert_custom_JenkinsServiceStatus_To_v1alpha_JenkinsServiceStatus(in *custom.JenkinsServiceStatus, out *JenkinsServiceStatus, s conversion.Scope) error {
	return autoConvert_custom_JenkinsServiceStatus_To_v1alpha_JenkinsServiceStatus(in, out, s)
}
